name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login YC
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: oauth
          password: AQAAAAAnRw_XAATuwYORpoaaSUS-gX4Z69c0DBM

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        run: |
          docker build -t cr.yandex/crpcl47e0kftruqbr27v/time:latest .
          docker push cr.yandex/crpcl47e0kftruqbr27v/time:latest
